/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Case.glb -k -M -j 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Case.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Tape001" rotation={[Math.PI, 1.571, 0]} scale={1.463}>
        <group name="tape" rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="tape001" geometry={nodes.tape001.geometry} material={materials.mat_tape} position={[0, 0.007, -0.155]} />
        </group>
      </group>
      <mesh name="front_frame" geometry={nodes.front_frame.geometry} material={materials.Material} scale={[1, 1, 1.5]} />
      <mesh name="right_side" geometry={nodes.right_side.geometry} material={materials['Material.001']} position={[-0.998, -0.201, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.181, 0.985, 1.489]} />
      <mesh name="left_side" geometry={nodes.left_side.geometry} material={materials['Material.002']} position={[0.996, -0.201, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.181, 0.985, 1.489]} />
      <mesh name="top" geometry={nodes.top.geometry} material={materials['Material.003']} position={[0, -0.317, 1.492]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.3]} />
      <mesh name="bottom" geometry={nodes.bottom.geometry} material={materials['Material.003']} position={[0, -0.317, -1.471]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.3]} />
      <mesh name="back_frame" geometry={nodes.back_frame.geometry} material={materials['Material.004']} position={[0, -0.378, 0]} scale={[1, 1, 1.5]} />
      <mesh name="Album_cover_front" geometry={nodes.Album_cover_front.geometry} material={nodes.Album_cover_front.material} position={[0, -0.023, 0]} scale={[0.936, 1, 1.462]} />
      <mesh name="Album_cover_back" geometry={nodes.Album_cover_back.geometry} material={nodes.Album_cover_back.material} position={[0, -0.374, 0]} scale={[0.936, 1, 1.462]} />
    </group>
  )
}

useGLTF.preload('/Case.glb')
