/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 walkmanc.glb -k -t -M -j 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Button2_low001_Walkman_0001: THREE.Mesh
    Button3_low001_Walkman_0001: THREE.Mesh
    Button4_low001_Walkman_0001: THREE.Mesh
    Button5_low001_Walkman_0001: THREE.Mesh
    Front_panel_low001_Walkman_0001: THREE.Mesh
    Inside10_low001_Walkman_0001: THREE.Mesh
    Inside11_low001_Walkman_0001: THREE.Mesh
    Inside12_low001_Walkman_0001: THREE.Mesh
    Inside3_low001_Walkman_0001: THREE.Mesh
    Inside4_low001_Walkman_0001: THREE.Mesh
    Inside5_low001_Walkman_0001: THREE.Mesh
    Inside8_low001_Walkman_0001: THREE.Mesh
    Jack1_low001_Walkman_0001: THREE.Mesh
    Jack_low001_Walkman_0001: THREE.Mesh
    Slider1_low001_Walkman_0001: THREE.Mesh
    Slider2_low001_Walkman_0001: THREE.Mesh
    Speaker_low001_Walkman_0001: THREE.Mesh
    Walkman1_low001_Walkman_0001: THREE.Mesh
    Walkman2_low001_Walkman_0001: THREE.Mesh
    Walkman3_low001_Walkman_0001: THREE.Mesh
    Walkman_inside2_low001_Walkman_0001: THREE.Mesh
    Walkman_inside_low001_Walkman_0001: THREE.Mesh
    CamFx_Bokeh001: THREE.Mesh
    CamFx_LensDirt001: THREE.Mesh
  }
  materials: {
    Walkman: THREE.MeshStandardMaterial
    ['Walkman.001']: THREE.MeshStandardMaterial
    ['.CamFx Bokeh.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/walkmanc.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera name="Camera002" makeDefault={false} far={1000} near={0.001} fov={20.408} position={[-7.52, 4.54, -0.018]} rotation={[-1.574, -0.99, 1.566]} />
      <PerspectiveCamera name="Camera003" makeDefault={false} far={1000} near={0.001} fov={20.408} position={[-5, 6.998, -0.018]} rotation={[-1.573, -0.593, 1.568]} />
      <mesh name="Button2_low001_Walkman_0001" geometry={nodes.Button2_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.58, -0.112, 0.909]} rotation={[0, 0, Math.PI]} />
      <mesh name="Button3_low001_Walkman_0001" geometry={nodes.Button3_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.58, -0.112, 0.909]} rotation={[0, 0, Math.PI]} />
      <mesh name="Button4_low001_Walkman_0001" geometry={nodes.Button4_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.58, -0.112, 0.554]} rotation={[0, 0, Math.PI]} />
      <mesh name="Button5_low001_Walkman_0001" geometry={nodes.Button5_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.599, 0.082, 0.576]} rotation={[0, 0, Math.PI]} />
      <mesh name="Front_panel_low001_Walkman_0001" geometry={nodes.Front_panel_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.613, 0.123, 0.011]} rotation={[0, 0, Math.PI]} />
      <mesh name="Inside10_low001_Walkman_0001" geometry={nodes.Inside10_low001_Walkman_0001.geometry} material={materials.Walkman} position={[0.134, 0.105, -0.946]} rotation={[0, 0, Math.PI]} />
      <mesh name="Inside11_low001_Walkman_0001" geometry={nodes.Inside11_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.379, 0.003, -0.071]} rotation={[0, 0, Math.PI]} />
      <mesh name="Inside12_low001_Walkman_0001" geometry={nodes.Inside12_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.043, 0.15, 0.659]} rotation={[0, 0, Math.PI]} />
      <mesh name="Inside3_low001_Walkman_0001" geometry={nodes.Inside3_low001_Walkman_0001.geometry} material={materials.Walkman} position={[0.177, 0.118, 0.198]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh name="Inside4_low001_Walkman_0001" geometry={nodes.Inside4_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.268, 0.071, 0.089]} rotation={[0, 0, Math.PI]} />
      <mesh name="Inside5_low001_Walkman_0001" geometry={nodes.Inside5_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.293, 0.046, 0.24]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh name="Inside8_low001_Walkman_0001" geometry={nodes.Inside8_low001_Walkman_0001.geometry} material={materials.Walkman} position={[0.144, 0.129, -0.923]} rotation={[0, 0, Math.PI]} />
      <mesh name="Jack1_low001_Walkman_0001" geometry={nodes.Jack1_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.584, -0.102, -0.777]} rotation={[Math.PI, -Math.PI / 2, 0]} />
      <mesh name="Jack_low001_Walkman_0001" geometry={nodes.Jack_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.607, -0.102, -0.777]} rotation={[Math.PI, -Math.PI / 2, 0]} />
      <mesh name="Slider1_low001_Walkman_0001" geometry={nodes.Slider1_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.627, -0.044, -0.225]} rotation={[0, 0, Math.PI]} />
      <mesh name="Slider2_low001_Walkman_0001" geometry={nodes.Slider2_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.627, -0.123, -0.099]} rotation={[0, 0, Math.PI]} />
      <mesh name="Speaker_low001_Walkman_0001" geometry={nodes.Speaker_low001_Walkman_0001.geometry} material={materials.Walkman} position={[-0.622, 0.117, 0.896]} rotation={[0, 0, Math.PI]} />
      <mesh name="Walkman1_low001_Walkman_0001" geometry={nodes.Walkman1_low001_Walkman_0001.geometry} material={materials['Walkman.001']} position={[-0.379, 0.003, -0.071]} rotation={[0, 0, Math.PI]} />
      <mesh name="Walkman2_low001_Walkman_0001" geometry={nodes.Walkman2_low001_Walkman_0001.geometry} material={materials['Walkman.001']} position={[0.136, 0, 0.011]} rotation={[0, 0, Math.PI]} />
      <mesh name="Walkman3_low001_Walkman_0001" geometry={nodes.Walkman3_low001_Walkman_0001.geometry} material={materials['Walkman.001']} position={[0.654, 0.138, -0.116]} rotation={[0, 0, -3.141]} />
      <mesh name="Walkman_inside2_low001_Walkman_0001" geometry={nodes.Walkman_inside2_low001_Walkman_0001.geometry} material={materials.Walkman} position={[0.136, 0, 0.011]} rotation={[0, 0, Math.PI]} />
      <mesh name="Walkman_inside_low001_Walkman_0001" geometry={nodes.Walkman_inside_low001_Walkman_0001.geometry} material={materials.Walkman} position={[0.136, 0, 0.011]} rotation={[0, 0, Math.PI]} />
      <mesh name="CamFx_Bokeh001" geometry={nodes.CamFx_Bokeh001.geometry} material={materials['.CamFx Bokeh.001']} />
      <mesh name="CamFx_LensDirt001" geometry={nodes.CamFx_LensDirt001.geometry} material={materials['.CamFx Bokeh.001']} />
    </group>
  )
}

useGLTF.preload('/walkmanc.glb')
