/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/walkman.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-13.586, 1.146, 0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Walkman2_low001_Walkman_0001.geometry}
              material={materials['Walkman.001']}
            />
            <group position={[-0.521, -0.141, -0.127]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Walkman3_low001_Walkman_0001.geometry}
                material={materials['Walkman.001']}
                position={[0.002, 0.003, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button2_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.716, 0.112, 0.897]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button3_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.716, 0.112, 0.897]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button4_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.716, 0.112, 0.543]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Button5_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.735, -0.082, 0.564]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_panel_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.749, -0.123, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside10_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.002, -0.105, -0.958]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside11_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.515, -0.003, -0.082]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside12_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.179, -0.15, 0.647]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside3_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[-0.041, -0.118, 0.187]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside4_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.404, -0.071, 0.077]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside5_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.429, -0.046, 0.228]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Inside8_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[-0.009, -0.129, -0.934]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Jack1_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.72, 0.102, -0.788]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Jack_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.743, 0.102, -0.788]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Slider1_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.763, 0.044, -0.236]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Slider2_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.763, 0.123, -0.111]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Speaker_low001_Walkman_0001.geometry}
              material={materials.Walkman}
              position={[0.758, -0.117, 0.885]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Walkman1_low001_Walkman_0001.geometry}
              material={materials['Walkman.001']}
              position={[0.515, -0.003, -0.082]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Walkman_inside2_low001_Walkman_0001.geometry}
              material={materials.Walkman}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Walkman_inside_low001_Walkman_0001.geometry}
              material={materials.Walkman}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/walkman.glb')
